pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Xuzker/Ansible.git'
            }
        }

        stage('Install Ansible') {
            steps {
                sh 'sudo apt-get update && sudo apt-get install -y ansible'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                sh 'ansible-playbook playbook.yml'
            }
        }
    }
}
